import { ROLES } from '../constants/roles';

export const INITIAL_CATEGORIES = [
  { id: 'cat-01', code: 'MOTION', name: 'Motion & Actuators', description: 'High-precision servos, stepper drives, linear slides, and encoders', skuCount: 3, status: 'ACTIVE' },
  { id: 'cat-02', code: 'PNEUMATICS', name: 'Hydraulics & Air', description: 'Directional solenoid valves, pneumatic cylinders, air prep regulators', skuCount: 2, status: 'ACTIVE' },
  { id: 'cat-03', code: 'SENSORS', name: 'Optics & Sensors', description: 'Laser distance sensors, photoelectric retroreflectives, proximity switches', skuCount: 2, status: 'ACTIVE' },
  { id: 'cat-04', code: 'POWER', name: 'Power & Energy', description: 'DIN rail power supplies 24V/48V, backup UPS batteries, current transformers', skuCount: 2, status: 'ACTIVE' },
  { id: 'cat-05', code: 'CONTROL', name: 'Logic & PLC', description: 'Modular logic controllers, programmable relays, fieldbus remote I/O', skuCount: 1, status: 'ACTIVE' },
  { id: 'cat-06', code: 'HARDWARE', name: 'Hardware & Bearings', description: 'Angular contact bearing sets, precision hardened shafts, structural brackets', skuCount: 2, status: 'ACTIVE' },
  { id: 'cat-07', code: 'CABLING', name: 'Cabling & Wiring', description: 'High-flex continuous drag chain cables, shielded motor leads, cable trays', skuCount: 2, status: 'ACTIVE' },
];

export const INITIAL_UOM = [
  { id: 'uom-01', name: 'Units / Pieces', symbol: 'ea', type: 'COUNT', decimals: 0, status: 'ACTIVE', isBase: true },
  { id: 'uom-02', name: 'Master Box / Carton', symbol: 'bx', type: 'PACKAGING', decimals: 0, status: 'ACTIVE', isBase: false },
  { id: 'uom-03', name: 'Standard Pallet', symbol: 'plt', type: 'BULK', decimals: 0, status: 'ACTIVE', isBase: false },
  { id: 'uom-04', name: 'Kilograms', symbol: 'kg', type: 'WEIGHT', decimals: 2, status: 'ACTIVE', isBase: false },
  { id: 'uom-05', name: 'Meters', symbol: 'm', type: 'LENGTH', decimals: 2, status: 'ACTIVE', isBase: false },
  { id: 'uom-06', name: 'Liters', symbol: 'L', type: 'VOLUME', decimals: 2, status: 'ACTIVE', isBase: false },
];

export const INITIAL_LOCATIONS = [
  { id: 'loc-01', code: 'A-01', warehouse: 'WH-01 Main DC (Bay Area)', zone: 'Zone A (Main Rack)', type: 'HIGH_BAY_RACK', maxCapacity: 80, currentQty: 60, sku: 'MTR-9002', status: 'OCCUPIED' },
  { id: 'loc-02', code: 'A-02', warehouse: 'WH-01 Main DC (Bay Area)', zone: 'Zone A (Main Rack)', type: 'HIGH_BAY_RACK', maxCapacity: 80, currentQty: 40, sku: 'MTR-9002', status: 'OCCUPIED' },
  { id: 'loc-03', code: 'A-03', warehouse: 'WH-01 Main DC (Bay Area)', zone: 'Zone A (Main Rack)', type: 'HIGH_BAY_RACK', maxCapacity: 80, currentQty: 0, sku: null, status: 'VACANT' },
  { id: 'loc-04', code: 'B-01', warehouse: 'WH-01 Main DC (Bay Area)', zone: 'Zone B (Bulk Bay)', type: 'BULK_STORAGE', maxCapacity: 50, currentQty: 28, sku: 'VLV-3011', status: 'OCCUPIED' },
  { id: 'loc-05', code: 'B-02', warehouse: 'WH-01 Main DC (Bay Area)', zone: 'Zone B (Bulk Bay)', type: 'BULK_STORAGE', maxCapacity: 50, currentQty: 45, sku: 'PWR-2410', status: 'OCCUPIED' },
  { id: 'loc-06', code: 'C-01', warehouse: 'WH-01 Main DC (Bay Area)', zone: 'Zone C (Rapid Dispatch)', type: 'STAGING_FLOOR', maxCapacity: 30, currentQty: 10, sku: 'MTR-9002', status: 'OCCUPIED' },
  { id: 'loc-07', code: 'C-02', warehouse: 'WH-01 Main DC (Bay Area)', zone: 'Zone C (Rapid Dispatch)', type: 'STAGING_FLOOR', maxCapacity: 30, currentQty: 0, sku: null, status: 'VACANT' },
  { id: 'loc-08', code: 'V-01', warehouse: 'WH-01 Main DC (Bay Area)', zone: 'Zone V (Secure Vault)', type: 'SECURE_LOCKBOX', maxCapacity: 75, currentQty: 64, sku: 'PLC-5500', status: 'OCCUPIED' },
  { id: 'loc-09', code: 'D-01', warehouse: 'WH-02 Midwest Regional Logistics Hub', zone: 'Zone A (Inbound Dock)', type: 'RECEIVING_DOCK', maxCapacity: 100, currentQty: 0, sku: null, status: 'VACANT' },
  { id: 'loc-10', code: 'D-02', warehouse: 'WH-02 Midwest Regional Logistics Hub', zone: 'Zone B (High-Bay)', type: 'HIGH_BAY_RACK', maxCapacity: 90, currentQty: 40, sku: 'SEN-1002', status: 'OCCUPIED' },
];

export const INITIAL_SYSTEM_USERS = [
  {
    id: 'usr-01',
    name: 'Sarah Chen',
    email: 'sarah.manager@stocksense.io',
    role: ROLES.INVENTORY_MANAGER,
    title: 'Operations & Inventory Lead',
    facility: 'WH-01 Main DC (San Francisco)',
    status: 'ACTIVE',
    avatar: 'SC',
    lastActive: 'Just now',
    createdAt: '2026-08-10',
    assignedDocks: ['Bay 01', 'Bay 02'],
    phone: '+1 (415) 890-1201',
  },
  {
    id: 'usr-02',
    name: 'Alex Rivera',
    email: 'alex.operator@stocksense.io',
    role: ROLES.WAREHOUSE_STAFF,
    title: 'Lead Receiving & Putaway Specialist',
    facility: 'WH-01 Main DC (San Francisco)',
    status: 'ACTIVE',
    avatar: 'AR',
    lastActive: '5 mins ago',
    createdAt: '2026-08-14',
    assignedDocks: ['Bay 01', 'Zone C'],
    phone: '+1 (415) 890-1202',
  },
  {
    id: 'usr-03',
    name: 'Marcus Vance',
    email: 'marcus.admin@stocksense.io',
    role: ROLES.ADMIN,
    title: 'Warehouse Systems Administrator',
    facility: 'Global Operations Headquarters',
    status: 'ACTIVE',
    avatar: 'MV',
    lastActive: 'Active Session',
    createdAt: '2026-07-01',
    assignedDocks: ['All Facilities'],
    phone: '+1 (415) 890-1200',
  },
  {
    id: 'usr-04',
    name: 'David Miller',
    email: 'david.manager@stocksense.io',
    role: ROLES.INVENTORY_MANAGER,
    title: 'Regional Logistics Hub Director',
    facility: 'WH-02 Midwest Regional Logistics Hub',
    status: 'ACTIVE',
    avatar: 'DM',
    lastActive: '2 hours ago',
    createdAt: '2026-08-18',
    assignedDocks: ['Gates A-H'],
    phone: '+1 (312) 555-8910',
  },
  {
    id: 'usr-05',
    name: 'Elena Rostova',
    email: 'elena.staff@stocksense.io',
    role: ROLES.WAREHOUSE_STAFF,
    title: 'Rapid Dispatch & Staging Lead',
    facility: 'WH-03 Southern Automated Facility',
    status: 'ACTIVE',
    avatar: 'ER',
    lastActive: '1 hour ago',
    createdAt: '2026-08-22',
    assignedDocks: ['Zone C', 'Dock 08'],
    phone: '+1 (214) 555-4321',
  },
  {
    id: 'usr-06',
    name: 'Liam Patel',
    email: 'liam.staff@stocksense.io',
    role: ROLES.WAREHOUSE_STAFF,
    title: 'Forklift & High-Bay Operator',
    facility: 'WH-01 Main DC (San Francisco)',
    status: 'ACTIVE',
    avatar: 'LP',
    lastActive: 'Yesterday',
    createdAt: '2026-09-02',
    assignedDocks: ['Rack A-02', 'Rack B-01'],
    phone: '+1 (415) 890-1209',
  },
  {
    id: 'usr-07',
    name: 'Maya Lin',
    email: 'maya.lin@candidate.io',
    role: ROLES.WAREHOUSE_STAFF,
    title: 'Floor Execution Operator Applicant',
    facility: 'WH-01 Main DC (San Francisco)',
    status: 'PENDING_APPROVAL',
    avatar: 'ML',
    lastActive: 'Pending Review',
    createdAt: '2026-09-26 10:15',
    notes: 'Signed up through employee portal. Awaiting administrator approval and warehouse terminal authorization.',
    phone: '+1 (415) 555-0199',
  },
  {
    id: 'usr-08',
    name: 'Carlos Gomez',
    email: 'carlos.gomez@candidate.io',
    role: ROLES.INVENTORY_MANAGER,
    title: 'Operations Manager Candidate',
    facility: 'WH-02 Midwest Regional Logistics Hub',
    status: 'PENDING_APPROVAL',
    avatar: 'CG',
    lastActive: 'Pending Review',
    createdAt: '2026-09-26 11:30',
    notes: 'Requested Manager Panel clearance for Midwest logistics and supplier purchase authorizations.',
    phone: '+1 (312) 555-0144',
  },
  {
    id: 'usr-09',
    name: 'Rachel Adams',
    email: 'rachel.temp@legacy.io',
    role: ROLES.WAREHOUSE_STAFF,
    title: 'Seasonal Contract Worker',
    facility: 'WH-01 Main DC (San Francisco)',
    status: 'SUSPENDED',
    avatar: 'RA',
    lastActive: '3 days ago',
    createdAt: '2026-08-01',
    notes: 'Seasonal contract expired. System access paused by administrator.',
    phone: '+1 (415) 890-1288',
  },
];

export const INITIAL_SYSTEM_ACTIVITY = [
  { id: 'act-01', timestamp: 'Today, 13:45', actor: 'Marcus Vance (Admin)', action: 'ROLE_CONFIG', details: 'Audited granular permission matrix for Warehouse Staff role.', severity: 'INFO' },
  { id: 'act-02', timestamp: 'Today, 13:30', actor: 'Sarah Chen (Manager)', action: 'APPROVAL', details: 'Approved stock discrepancy adjustment ADJ-1589 on SKU MTR-9002.', severity: 'SUCCESS' },
  { id: 'act-03', timestamp: 'Today, 13:12', actor: 'System Gatekeeper', action: 'SIGNUP_PENDING', details: 'New registration received from Carlos Gomez (Awaiting admin approval).', severity: 'WARNING' },
  { id: 'act-04', timestamp: 'Today, 12:40', actor: 'Alex Rivera (Staff)', action: 'RECEIVING', details: 'Confirmed inbound PO-9401 (30 units MTR-9002 at Bay 01).', severity: 'INFO' },
  { id: 'act-05', timestamp: 'Today, 11:15', actor: 'Marcus Vance (Admin)', action: 'SECURITY', details: 'Suspended legacy contractor session for Rachel Adams.', severity: 'WARNING' },
  { id: 'act-06', timestamp: 'Today, 10:00', actor: 'System Engine', action: 'LEDGER_AUDIT', details: 'Automatic ledger reconciliation completed with 0 drift.', severity: 'SUCCESS' },
];

export const INITIAL_SYSTEM_SETTINGS = {
  systemName: 'StockSense Cloud WMS Engine',
  version: 'v2.4-enterprise',
  maintenanceMode: false,
  requireApprovalForNewUsers: true,
  discrepancyApprovalThreshold: 5,
  sessionInactivityTimeoutMins: 30,
  automaticLedgerSync: true,
  enforceDoubleEntryAccounting: true,
  defaultWarehouseId: 'wh-01',
  supportEmail: 'ops.admin@stocksense.io',
};

