/**
 * StockSense Comprehensive Industrial Dataset
 * Fully populated dummy data for all modules: Products, Receipts, Transfers, Deliveries, Adjustments, Ledger, Warehouse, Settings.
 */

export const INITIAL_PRODUCTS = [
  {
    id: 'prod-001',
    sku: 'MTR-9002',
    name: 'Industrial High-Torque Servo Motor 48V',
    category: 'Motion & Actuators',
    unitCost: 320.0,
    unitPrice: 485.0,
    onHand: 120,
    allocated: 20,
    available: 100,
    minThreshold: 50,
    status: 'IN_STOCK',
    primaryLocation: 'Rack A-02',
    uom: 'Units',
    barcode: '8401928301',
    weight: '4.2 kg',
    locations: [
      { zone: 'Zone A (Main Rack)', bin: 'A-02', qty: 100 },
      { zone: 'Zone C (Rapid Dispatch)', bin: 'C-04', qty: 20 },
    ],
  },
  {
    id: 'prod-002',
    sku: 'VLV-3011',
    name: 'Pneumatic Solenoid Control Valve 24V',
    category: 'Hydraulics & Air',
    unitCost: 85.0,
    unitPrice: 140.0,
    onHand: 28,
    allocated: 15,
    available: 13,
    minThreshold: 40,
    status: 'LOW_STOCK',
    primaryLocation: 'Rack B-01',
    uom: 'Units',
    barcode: '8401928302',
    weight: '1.1 kg',
    locations: [
      { zone: 'Zone B (Bulk Bay)', bin: 'B-01', qty: 28 },
    ],
  },
  {
    id: 'prod-003',
    sku: 'SEN-1002',
    name: 'Optical Laser Distance Sensor IP67',
    category: 'Sensors & Vision',
    unitCost: 195.0,
    unitPrice: 290.0,
    onHand: 8,
    allocated: 8,
    available: 0,
    minThreshold: 25,
    status: 'OUT_OF_STOCK',
    primaryLocation: 'Rack C-03',
    uom: 'Units',
    barcode: '8401928303',
    weight: '0.35 kg',
    locations: [
      { zone: 'Zone C (Rapid Dispatch)', bin: 'C-03', qty: 8 },
    ],
  },
  {
    id: 'prod-004',
    sku: 'PLC-5500',
    name: 'Modular Programmable Logic Controller 32-I/O',
    category: 'Automation & Controls',
    unitCost: 850.0,
    unitPrice: 1250.0,
    onHand: 64,
    allocated: 12,
    available: 52,
    minThreshold: 20,
    status: 'IN_STOCK',
    primaryLocation: 'Vault 01',
    uom: 'Units',
    barcode: '8401928304',
    weight: '2.8 kg',
    locations: [
      { zone: 'Secure Storage Vault', bin: 'V-01', qty: 64 },
    ],
  },
  {
    id: 'prod-005',
    sku: 'CAB-8820',
    name: 'Shielded High-Flex Drag Chain Cable 100m',
    category: 'Cabling & Power',
    unitCost: 110.0,
    unitPrice: 180.0,
    onHand: 42,
    allocated: 5,
    available: 37,
    minThreshold: 30,
    status: 'IN_STOCK',
    primaryLocation: 'Rack D-02',
    uom: 'Rolls',
    barcode: '8401928305',
    weight: '8.5 kg',
    locations: [
      { zone: 'Zone D (Raw Materials)', bin: 'D-02', qty: 42 },
    ],
  },
  {
    id: 'prod-006',
    sku: 'BEA-7204',
    name: 'High-Precision Angular Contact Bearing Set',
    category: 'Mechanical Hardware',
    unitCost: 45.0,
    unitPrice: 78.0,
    onHand: 180,
    allocated: 30,
    available: 150,
    minThreshold: 60,
    status: 'IN_STOCK',
    primaryLocation: 'Bin A-14',
    uom: 'Sets',
    barcode: '8401928306',
    weight: '0.8 kg',
    locations: [
      { zone: 'Zone A (Main Rack)', bin: 'A-14', qty: 180 },
    ],
  },
  {
    id: 'prod-007',
    sku: 'HMI-1080',
    name: 'Industrial Touchscreen Operator Panel 10.4"',
    category: 'Automation & Controls',
    unitCost: 420.0,
    unitPrice: 650.0,
    onHand: 19,
    allocated: 6,
    available: 13,
    minThreshold: 20,
    status: 'LOW_STOCK',
    primaryLocation: 'Vault 02',
    uom: 'Units',
    barcode: '8401928307',
    weight: '1.9 kg',
    locations: [
      { zone: 'Secure Storage Vault', bin: 'V-02', qty: 19 },
    ],
  },
  {
    id: 'prod-008',
    sku: 'PWR-2410',
    name: 'DIN-Rail Regulated Power Supply 24V 10A',
    category: 'Cabling & Power',
    unitCost: 72.0,
    unitPrice: 115.0,
    onHand: 85,
    allocated: 10,
    available: 75,
    minThreshold: 35,
    status: 'IN_STOCK',
    primaryLocation: 'Rack B-08',
    uom: 'Units',
    barcode: '8401928308',
    weight: '1.2 kg',
    locations: [
      { zone: 'Zone B (Bulk Bay)', bin: 'B-08', qty: 85 },
    ],
  },
];

export const INITIAL_RECEIPTS_QUEUE = [
  {
    id: 'rec-01',
    poNumber: 'PO-9401',
    supplier: 'Apex Precision Motors Ltd',
    sku: 'MTR-9002',
    productName: 'Industrial Servo Motor',
    expectedQty: 30,
    dock: 'Bay 01 - Receiving',
    targetLocation: 'Rack A-02',
    eta: 'Today, 10:30 AM',
    carrier: 'FastFreight Global',
    status: 'READY_TO_RECEIVE',
  },
  {
    id: 'rec-02',
    poNumber: 'PO-9402',
    supplier: 'Kinetix Fluid Power Inc',
    sku: 'VLV-3011',
    productName: 'Pneumatic Solenoid Valve',
    expectedQty: 40,
    dock: 'Bay 02 - Receiving',
    targetLocation: 'Rack B-01',
    eta: 'Today, 01:15 PM',
    carrier: 'DHL Freight',
    status: 'IN_TRANSIT',
  },
  {
    id: 'rec-03',
    poNumber: 'PO-9403',
    supplier: 'Spectra Optics Corp',
    sku: 'SEN-1002',
    productName: 'Laser Distance Sensor',
    expectedQty: 25,
    dock: 'Bay 01 - Receiving',
    targetLocation: 'Rack C-03',
    eta: 'Tomorrow, 09:00 AM',
    carrier: 'FedEx Priority',
    status: 'SCHEDULED',
  },
  {
    id: 'rec-04',
    poNumber: 'PO-9398',
    supplier: 'Schneider Automation AG',
    sku: 'PLC-5500',
    productName: 'Modular Logic Controller',
    expectedQty: 15,
    dock: 'Bay 01 - Receiving',
    targetLocation: 'Vault 01',
    eta: 'Yesterday, 04:00 PM',
    carrier: 'UPS Air Freight',
    status: 'RECEIVED',
    receivedAt: 'Sep 25, 2026, 04:15 PM',
    receivedBy: 'Alex Rivera (Staff)',
  },
  {
    id: 'rec-05',
    poNumber: 'PO-9395',
    supplier: 'Alpha Power Solutions',
    sku: 'PWR-2410',
    productName: 'Power Supply 24V',
    expectedQty: 50,
    dock: 'Bay 02 - Receiving',
    targetLocation: 'Rack B-08',
    eta: 'Sep 24, 2026',
    carrier: 'Estes Express',
    status: 'RECEIVED',
    receivedAt: 'Sep 24, 2026, 02:45 PM',
    receivedBy: 'Sarah Chen (Manager)',
  },
];

export const INITIAL_TRANSFERS_QUEUE = [
  {
    id: 'tr-01',
    transferNo: 'TR-7801',
    sku: 'MTR-9002',
    productName: 'Industrial Servo Motor',
    qty: 15,
    fromLocation: 'Rack A-02 (Bulk)',
    toLocation: 'Zone C (Rapid Dispatch)',
    priority: 'HIGH',
    reason: 'Stage for outgoing order SO-9102',
    status: 'SCHEDULED',
    requestedBy: 'Sarah Chen',
  },
  {
    id: 'tr-02',
    transferNo: 'TR-7802',
    sku: 'CAB-8820',
    productName: 'Shielded Drag Cable',
    qty: 10,
    fromLocation: 'Rack D-02 (Raw)',
    toLocation: 'Zone B (Assembly Bin 04)',
    priority: 'MEDIUM',
    reason: 'Replenish active packing line',
    status: 'SCHEDULED',
    requestedBy: 'Alex Rivera',
  },
  {
    id: 'tr-03',
    transferNo: 'TR-7803',
    sku: 'VLV-3011',
    productName: 'Pneumatic Solenoid Valve',
    qty: 8,
    fromLocation: 'Rack B-01',
    toLocation: 'Zone C (Rapid Dispatch)',
    priority: 'HIGH',
    reason: 'Buffer inventory replenishment',
    status: 'SCHEDULED',
    requestedBy: 'Sarah Chen',
  },
  {
    id: 'tr-04',
    transferNo: 'TR-7798',
    sku: 'BEA-7204',
    productName: 'Angular Bearing Set',
    qty: 40,
    fromLocation: 'Bay 01 (Inbound)',
    toLocation: 'Bin A-14 (Racks)',
    priority: 'NORMAL',
    reason: 'Putaway from PO-9390',
    status: 'COMPLETED',
    completedAt: 'Today, 08:30 AM',
    requestedBy: 'Alex Rivera',
  },
  {
    id: 'tr-05',
    transferNo: 'TR-7795',
    sku: 'HMI-1080',
    productName: 'Touchscreen Panel',
    qty: 5,
    fromLocation: 'Vault 02',
    toLocation: 'Zone C (Rapid Dispatch)',
    priority: 'HIGH',
    reason: 'Staged for customer pickup',
    status: 'COMPLETED',
    completedAt: 'Yesterday, 03:10 PM',
    requestedBy: 'Sarah Chen',
  },
];

export const INITIAL_DELIVERIES_QUEUE = [
  {
    id: 'del-01',
    orderNo: 'SO-9102',
    customer: 'Tesla Gigafactory Texas',
    sku: 'MTR-9002',
    productName: 'Industrial Servo Motor',
    qty: 10,
    sourceLocation: 'Zone C (Rapid Dispatch)',
    carrier: 'DHL Express Freight',
    deadline: 'Today, 03:00 PM',
    destination: 'Austin, TX, USA',
    status: 'READY_TO_DISPATCH',
  },
  {
    id: 'del-02',
    orderNo: 'SO-9103',
    customer: 'Boeing Defense & Space',
    sku: 'PLC-5500',
    productName: 'Modular Logic Controller',
    qty: 4,
    sourceLocation: 'Vault 01 (Secure)',
    carrier: 'FedEx Secure Freight',
    deadline: 'Today, 05:30 PM',
    destination: 'Seattle, WA, USA',
    status: 'PACKED',
  },
  {
    id: 'del-03',
    orderNo: 'SO-9104',
    customer: 'Applied Materials Inc',
    sku: 'SEN-1002',
    productName: 'Laser Distance Sensor',
    qty: 8,
    sourceLocation: 'Zone C (Rapid Dispatch)',
    carrier: 'UPS Air Cargo',
    deadline: 'Tomorrow, 11:00 AM',
    destination: 'Santa Clara, CA, USA',
    status: 'AWAITING_STOCK',
  },
  {
    id: 'del-04',
    orderNo: 'SO-9098',
    customer: 'Siemens Industrial Automation',
    sku: 'PWR-2410',
    productName: 'Power Supply 24V',
    qty: 20,
    sourceLocation: 'Rack B-08',
    carrier: 'Old Dominion Freight',
    deadline: 'Yesterday',
    destination: 'Atlanta, GA, USA',
    status: 'DISPATCHED',
    dispatchedAt: 'Yesterday, 04:45 PM',
  },
  {
    id: 'del-05',
    orderNo: 'SO-9095',
    customer: 'Lockheed Martin Aeronautics',
    sku: 'CAB-8820',
    productName: 'Shielded Drag Cable',
    qty: 12,
    sourceLocation: 'Rack D-02',
    carrier: 'FedEx Custom Critical',
    deadline: 'Sep 24, 2026',
    destination: 'Fort Worth, TX, USA',
    status: 'DISPATCHED',
    dispatchedAt: 'Sep 24, 2026, 01:20 PM',
  },
];

export const INITIAL_ADJUSTMENTS = [
  {
    id: 'adj-01',
    adjNumber: 'ADJ-0041',
    sku: 'CAB-8820',
    productName: 'Shielded Drag Chain Cable',
    location: 'Rack D-02',
    systemQty: 44,
    physicalQty: 42,
    delta: -2,
    reason: 'Physical Damage / Forklift Snag',
    operator: 'Sarah Chen (Manager)',
    approvedBy: 'Sarah Chen',
    timestamp: 'Today, 07:15 AM',
    status: 'APPROVED',
  },
  {
    id: 'adj-02',
    adjNumber: 'ADJ-0040',
    sku: 'BEA-7204',
    productName: 'Angular Bearing Set',
    location: 'Bin A-14',
    systemQty: 175,
    physicalQty: 180,
    delta: +5,
    reason: 'Found Unrecorded Stock during Cycle Count',
    operator: 'Alex Rivera (Staff)',
    approvedBy: 'Sarah Chen (Manager)',
    timestamp: 'Yesterday, 05:40 PM',
    status: 'APPROVED',
  },
  {
    id: 'adj-03',
    adjNumber: 'ADJ-0039',
    sku: 'VLV-3011',
    productName: 'Pneumatic Control Valve',
    location: 'Rack B-01',
    systemQty: 30,
    physicalQty: 28,
    delta: -2,
    reason: 'Defective Seal Scrap Write-Off',
    operator: 'Alex Rivera (Staff)',
    approvedBy: 'Sarah Chen (Manager)',
    timestamp: 'Sep 24, 2026, 11:20 AM',
    status: 'APPROVED',
  },
  {
    id: 'adj-04',
    adjNumber: 'ADJ-0038',
    sku: 'HMI-1080',
    productName: 'Touchscreen Panel',
    location: 'Vault 02',
    systemQty: 20,
    physicalQty: 19,
    delta: -1,
    reason: 'Factory Inspection Sample Pull',
    operator: 'Marcus Vance (Admin)',
    approvedBy: 'Marcus Vance (Admin)',
    timestamp: 'Sep 23, 2026, 09:30 AM',
    status: 'APPROVED',
  },
];

export const INITIAL_LEDGER = [
  {
    id: 'tx-1094',
    timestamp: '10 mins ago',
    type: 'RECEIPT',
    reference: 'PO-8821',
    sku: 'MTR-9002',
    productName: 'Servo Motor',
    source: 'Inbound Dock A',
    destination: 'Rack A-02',
    qtyChange: +50,
    balanceAfter: 120,
    operator: 'Alex Rivera (Staff)',
    note: 'Supplier PO verified & put away',
  },
  {
    id: 'tx-1093',
    timestamp: '42 mins ago',
    type: 'TRANSFER',
    reference: 'TR-4102',
    sku: 'VLV-3011',
    productName: 'Pneumatic Valve',
    source: 'Rack B-01',
    destination: 'Zone C - Rapid Dispatch',
    qtyChange: 20,
    isRelocation: true,
    balanceAfter: 28,
    operator: 'Alex Rivera (Staff)',
    note: 'Staged for customer picking queue',
  },
  {
    id: 'tx-1092',
    timestamp: '2 hours ago',
    type: 'DELIVERY',
    reference: 'SO-9022',
    sku: 'SEN-1002',
    productName: 'Laser Sensor',
    source: 'Zone C - Rapid Dispatch',
    destination: 'Carrier Outbound (FedEx Freight)',
    qtyChange: -15,
    balanceAfter: 8,
    operator: 'Sarah Chen (Manager)',
    note: 'Priority order dispatch complete',
  },
  {
    id: 'tx-1091',
    timestamp: '3 hours ago',
    type: 'ADJUSTMENT',
    reference: 'ADJ-0041',
    sku: 'CAB-8820',
    productName: 'Flex Cable',
    source: 'Rack D-02',
    destination: 'Scrap / Discard Bin',
    qtyChange: -2,
    balanceAfter: 42,
    operator: 'Sarah Chen (Manager)',
    note: 'Forklift snag damage logged during cycle count',
  },
  {
    id: 'tx-1090',
    timestamp: 'Yesterday, 04:15 PM',
    type: 'RECEIPT',
    reference: 'PO-9398',
    sku: 'PLC-5500',
    productName: 'Logic Controller',
    source: 'Receiving Dock B',
    destination: 'Vault 01',
    qtyChange: +15,
    balanceAfter: 64,
    operator: 'Alex Rivera (Staff)',
    note: 'High-value shipment received and sealed in vault',
  },
  {
    id: 'tx-1089',
    timestamp: 'Yesterday, 02:45 PM',
    type: 'DELIVERY',
    reference: 'SO-9098',
    sku: 'PWR-2410',
    productName: 'Power Supply 24V',
    source: 'Rack B-08',
    destination: 'Customer: Siemens Automation',
    qtyChange: -20,
    balanceAfter: 85,
    operator: 'Sarah Chen (Manager)',
    note: 'Full pallet dispatch picked and shipped',
  },
  {
    id: 'tx-1088',
    timestamp: 'Yesterday, 11:30 AM',
    type: 'TRANSFER',
    reference: 'TR-7798',
    sku: 'BEA-7204',
    productName: 'Bearing Set',
    source: 'Bay 01 Receiving',
    destination: 'Bin A-14',
    qtyChange: 40,
    isRelocation: true,
    balanceAfter: 180,
    operator: 'Alex Rivera (Staff)',
    note: 'Putaway completed from morning receipt',
  },
  {
    id: 'tx-1087',
    timestamp: 'Sep 24, 2026, 05:10 PM',
    type: 'ADJUSTMENT',
    reference: 'ADJ-0040',
    sku: 'BEA-7204',
    productName: 'Bearing Set',
    source: 'Unrecorded Bin Overflow',
    destination: 'Bin A-14',
    qtyChange: +5,
    balanceAfter: 180,
    operator: 'Alex Rivera (Staff)',
    note: 'Found 5 additional sets in unassigned staging tote',
  },
];

export const INITIAL_METRICS = {
  totalInventoryValuation: 428950,
  valuationGrowthPct: 4.8,
  totalStockUnits: 1420,
  lowStockCount: 4,
  criticalOutCount: 1,
  activeInboundPOs: 6,
  inboundUnitsPending: 240,
  pendingDeliveriesCount: 14,
  outboundUnitsPending: 185,
  scheduledTransfersCount: 8,
  transferUnitsScheduled: 110,
  ledgerSyncAccuracy: 99.98,
  totalLedgerEntries: 1842,
  warehouseCapacityPct: 76.5,
  dailyFulfillmentSlaPct: 98.4,
};

export const INITIAL_ZONES = [
  {
    id: 'zone-a',
    code: 'ZONE-A',
    name: 'Zone A (High-Bay Pallet Racks)',
    aisles: 'Aisles 01 - 06',
    binsTotal: 500,
    binsOccupied: 390,
    occupancy: 78,
    capacity: '390 / 500 Bins',
    primaryItems: 'Servo Motors, Bearing Sets, Heavy Mechanicals',
    temp: '20.5°C',
    status: 'Optimal',
  },
  {
    id: 'zone-b',
    code: 'ZONE-B',
    name: 'Zone B (Bulk Storage & Hydraulics)',
    aisles: 'Aisles 07 - 12',
    binsTotal: 400,
    binsOccupied: 256,
    occupancy: 64,
    capacity: '256 / 400 Bins',
    primaryItems: 'Pneumatic Valves, Power Supplies, Hardware Kits',
    temp: '19.8°C',
    status: 'Optimal',
  },
  {
    id: 'zone-c',
    code: 'ZONE-C',
    name: 'Zone C (Rapid Dispatch & Outbound)',
    aisles: 'Corridors C01 - C04',
    binsTotal: 200,
    binsOccupied: 182,
    occupancy: 91,
    capacity: '182 / 200 Bins',
    primaryItems: 'Fast-Moving SKUs, Staged Delivery Orders',
    temp: '21.0°C',
    status: 'Warning',
  },
  {
    id: 'zone-d',
    code: 'ZONE-D',
    name: 'Zone D (Raw Materials & Cable Reeling)',
    aisles: 'Aisles 13 - 16',
    binsTotal: 300,
    binsOccupied: 126,
    occupancy: 42,
    capacity: '126 / 300 Bins',
    primaryItems: 'Heavy Spools, Shielded Cables, Structural Metals',
    temp: '18.5°C',
    status: 'Low',
  },
  {
    id: 'zone-v',
    code: 'VAULT-SEC',
    name: 'Secure Vault (High-Value Electronics)',
    aisles: 'Vault Chambers V01 - V04',
    binsTotal: 100,
    binsOccupied: 83,
    occupancy: 83,
    capacity: '83 / 100 Bins',
    primaryItems: 'PLCs, Touch Panels, Microcontroller Boards',
    temp: '19.0°C (Climate-Controlled)',
    status: 'Optimal',
  },
];

export const INITIAL_SETTINGS = {
  facilityName: 'Main Distribution Center (WH-01)',
  facilityCode: 'WH-01',
  operatingHours: '06:00 - 22:00 (Two 8-Hour Shifts)',
  defaultReceivingBay: 'Bay 01 - Receiving Inbound',
  defaultDispatchDock: 'Dock 04 - Outbound Express',
  lowStockThresholdPct: 20,
  criticalThresholdUnits: 5,
  doubleEntryEnforcement: 'STRICT (Ledger validation required for every delta)',
  reconciliationAuditCycle: 'DAILY (Continuous cycle counting)',
  notificationEmail: 'alerts.ops@stocksense.io',
};
